/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiAdminAuthRouteImport } from './routes/api/admin-auth'
import { Route as ApiLeadEmailRouteImport } from './routes/api/lead-email'
import { Route as ApiLeadWebhookRouteImport } from './routes/api/lead-webhook'
import { Route as ApiTrialStartRouteImport } from './routes/api/trial-start'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as ApiOgSlugRouteImport } from './routes/api/og.$slug'
import { Route as ApiVcardSlugRouteImport } from './routes/api/vcard.$slug'
import { Route as ApiWalletSlugRouteImport } from './routes/api/wallet.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthRoute = ApiAdminAuthRouteImport.update({
  id: '/api/admin-auth',
  path: '/api/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadEmailRoute = ApiLeadEmailRouteImport.update({
  id: '/api/lead-email',
  path: '/api/lead-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadWebhookRoute = ApiLeadWebhookRouteImport.update({
  id: '/api/lead-webhook',
  path: '/api/lead-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrialStartRoute = ApiTrialStartRouteImport.update({
  id: '/api/trial-start',
  path: '/api/trial-start',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgSlugRoute = ApiOgSlugRouteImport.update({
  id: '/api/og/$slug',
  path: '/api/og/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVcardSlugRoute = ApiVcardSlugRouteImport.update({
  id: '/api/vcard/$slug',
  path: '/api/vcard/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletSlugRoute = ApiWalletSlugRouteImport.update({
  id: '/api/wallet/$slug',
  path: '/api/wallet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/lead-email': typeof ApiLeadEmailRoute
  '/api/lead-webhook': typeof ApiLeadWebhookRoute
  '/api/trial-start': typeof ApiTrialStartRoute
  '/c/$slug': typeof CSlugRoute
  '/t/$token': typeof TTokenRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/api/vcard/$slug': typeof ApiVcardSlugRoute
  '/api/wallet/$slug': typeof ApiWalletSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/lead-email': typeof ApiLeadEmailRoute
  '/api/lead-webhook': typeof ApiLeadWebhookRoute
  '/api/trial-start': typeof ApiTrialStartRoute
  '/c/$slug': typeof CSlugRoute
  '/t/$token': typeof TTokenRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/api/vcard/$slug': typeof ApiVcardSlugRoute
  '/api/wallet/$slug': typeof ApiWalletSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/lead-email': typeof ApiLeadEmailRoute
  '/api/lead-webhook': typeof ApiLeadWebhookRoute
  '/api/trial-start': typeof ApiTrialStartRoute
  '/c/$slug': typeof CSlugRoute
  '/t/$token': typeof TTokenRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/api/vcard/$slug': typeof ApiVcardSlugRoute
  '/api/wallet/$slug': typeof ApiWalletSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/builder'
    | '/dashboard'
    | '/api/admin-auth'
    | '/api/lead-email'
    | '/api/lead-webhook'
    | '/api/trial-start'
    | '/c/$slug'
    | '/t/$token'
    | '/api/og/$slug'
    | '/api/vcard/$slug'
    | '/api/wallet/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/builder'
    | '/dashboard'
    | '/api/admin-auth'
    | '/api/lead-email'
    | '/api/lead-webhook'
    | '/api/trial-start'
    | '/c/$slug'
    | '/t/$token'
    | '/api/og/$slug'
    | '/api/vcard/$slug'
    | '/api/wallet/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/builder'
    | '/dashboard'
    | '/api/admin-auth'
    | '/api/lead-email'
    | '/api/lead-webhook'
    | '/api/trial-start'
    | '/c/$slug'
    | '/t/$token'
    | '/api/og/$slug'
    | '/api/vcard/$slug'
    | '/api/wallet/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BuilderRoute: typeof BuilderRoute
  DashboardRoute: typeof DashboardRoute
  ApiAdminAuthRoute: typeof ApiAdminAuthRoute
  ApiLeadEmailRoute: typeof ApiLeadEmailRoute
  ApiLeadWebhookRoute: typeof ApiLeadWebhookRoute
  ApiTrialStartRoute: typeof ApiTrialStartRoute
  CSlugRoute: typeof CSlugRoute
  TTokenRoute: typeof TTokenRoute
  ApiOgSlugRoute: typeof ApiOgSlugRoute
  ApiVcardSlugRoute: typeof ApiVcardSlugRoute
  ApiWalletSlugRoute: typeof ApiWalletSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-auth': {
      id: '/api/admin-auth'
      path: '/api/admin-auth'
      fullPath: '/api/admin-auth'
      preLoaderRoute: typeof ApiAdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead-email': {
      id: '/api/lead-email'
      path: '/api/lead-email'
      fullPath: '/api/lead-email'
      preLoaderRoute: typeof ApiLeadEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead-webhook': {
      id: '/api/lead-webhook'
      path: '/api/lead-webhook'
      fullPath: '/api/lead-webhook'
      preLoaderRoute: typeof ApiLeadWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trial-start': {
      id: '/api/trial-start'
      path: '/api/trial-start'
      fullPath: '/api/trial-start'
      preLoaderRoute: typeof ApiTrialStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$slug': {
      id: '/api/og/$slug'
      path: '/api/og/$slug'
      fullPath: '/api/og/$slug'
      preLoaderRoute: typeof ApiOgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vcard/$slug': {
      id: '/api/vcard/$slug'
      path: '/api/vcard/$slug'
      fullPath: '/api/vcard/$slug'
      preLoaderRoute: typeof ApiVcardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/$slug': {
      id: '/api/wallet/$slug'
      path: '/api/wallet/$slug'
      fullPath: '/api/wallet/$slug'
      preLoaderRoute: typeof ApiWalletSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BuilderRoute: BuilderRoute,
  DashboardRoute: DashboardRoute,
  ApiAdminAuthRoute: ApiAdminAuthRoute,
  ApiLeadEmailRoute: ApiLeadEmailRoute,
  ApiLeadWebhookRoute: ApiLeadWebhookRoute,
  ApiTrialStartRoute: ApiTrialStartRoute,
  CSlugRoute: CSlugRoute,
  TTokenRoute: TTokenRoute,
  ApiOgSlugRoute: ApiOgSlugRoute,
  ApiVcardSlugRoute: ApiVcardSlugRoute,
  ApiWalletSlugRoute: ApiWalletSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
